### ISSUE TITLE
RPI4 not correctly recognized

### ISSUE THREAD

**Issue by bartdorlandt** [andrewrothstein/ansible-starship#4]
Hi Andrew,

I just tried your role and it seems RPI4 (aarch64) is marked as gnu instead of musl. 
I tried to see if I could do a PR myself, but not sure how to map it. 

Here are details for the manual installation. 

```
$ curl -sS https://starship.rs/install.sh | sh

  Configuration
> Bin directory: /usr/local/bin
> Platform:      unknown-linux-musl
> Arch:          aarch64

> Tarball URL: https://github.com/starship/starship/releases/latest/download/starship-aarch64-unknown-linux-musl.tar.gz
```

Hope this helps.

**Comment by andrewrothstein** [comment]
if ur targeting Alpine, the role substitutes the os map appropriately [here](https://github.com/andrewrothstein/ansible-starship/blob/master/vars/Alpine.yml#L2)
